"""Add core tables

Revision ID: 5b6f84cbc5db
Revises: merge_heads_20260109
Create Date: 2026-01-09 18:09:00.265829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b6f84cbc5db'
down_revision = 'merge_heads_20260109'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_uk', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('name_de', sa.String(), nullable=True),
    sa.Column('name_pl', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description_uk', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('culture_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('daily_sales_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('total_items_sold', sa.Integer(), nullable=True),
    sa.Column('pending_orders', sa.Integer(), nullable=True),
    sa.Column('paid_orders', sa.Integer(), nullable=True),
    sa.Column('shipped_orders', sa.Integer(), nullable=True),
    sa.Column('delivered_orders', sa.Integer(), nullable=True),
    sa.Column('cancelled_orders', sa.Integer(), nullable=True),
    sa.Column('stripe_revenue', sa.Float(), nullable=True),
    sa.Column('p24_revenue', sa.Float(), nullable=True),
    sa.Column('blik_revenue', sa.Float(), nullable=True),
    sa.Column('avg_order_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_sales_stats_date'), 'daily_sales_stats', ['date'], unique=True)
    op.create_index(op.f('ix_daily_sales_stats_id'), 'daily_sales_stats', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(), nullable=False),
    sa.Column('customer_email', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('shipping_address_line1', sa.String(), nullable=False),
    sa.Column('shipping_address_line2', sa.String(), nullable=True),
    sa.Column('shipping_city', sa.String(), nullable=False),
    sa.Column('shipping_postal_code', sa.String(), nullable=False),
    sa.Column('shipping_country', sa.String(), nullable=False),
    sa.Column('billing_address_line1', sa.String(), nullable=True),
    sa.Column('billing_address_line2', sa.String(), nullable=True),
    sa.Column('billing_city', sa.String(), nullable=True),
    sa.Column('billing_postal_code', sa.String(), nullable=True),
    sa.Column('billing_country', sa.String(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('bonus_points_used', sa.Float(), nullable=True),
    sa.Column('bonus_points_earned', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('payment_method', sa.Enum('STRIPE', 'PRZELEWY24', 'BLIK', 'BANK_TRANSFER', name='paymentmethod'), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=True),
    sa.Column('payment_intent_id', sa.String(), nullable=True),
    sa.Column('payment_details', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='orderstatus'), nullable=True),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('tracking_number', sa.String(), nullable=True),
    sa.Column('tracking_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verification_token', sa.String(), nullable=True),
    sa.Column('email_verification_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_reset_code', sa.String(), nullable=True),
    sa.Column('password_reset_code_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_reset_code_attempts', sa.Integer(), nullable=True),
    sa.Column('two_factor_secret', sa.String(), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('loyalty_status', sa.Enum('HUMAN', 'ELF', 'DWARF', name='userstatus'), nullable=True),
    sa.Column('bonus_points', sa.Float(), nullable=True),
    sa.Column('total_spent', sa.Float(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('email_notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_email_verification_token'), 'users', ['email_verification_token'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_password_reset_code'), 'users', ['password_reset_code'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_uk', sa.String(), nullable=False),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('title_de', sa.String(), nullable=True),
    sa.Column('title_pl', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description_uk', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_de', sa.Text(), nullable=True),
    sa.Column('description_pl', sa.Text(), nullable=True),
    sa.Column('legend_title_uk', sa.String(), nullable=True),
    sa.Column('legend_title_en', sa.String(), nullable=True),
    sa.Column('legend_content_uk', sa.Text(), nullable=True),
    sa.Column('legend_content_en', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('compare_at_price', sa.Float(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('materials', sa.JSON(), nullable=True),
    sa.Column('specifications', sa.JSON(), nullable=True),
    sa.Column('is_handmade', sa.Boolean(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('symbols', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_made_to_order', sa.Boolean(), nullable=True),
    sa.Column('made_to_order_duration', sa.String(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('meta_keywords', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_index(op.f('ix_products_title_uk'), 'products', ['title_uk'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('INPOST', 'POCZTA_POLSKA', 'DHL', 'NOVA_POSHTA', name='shippingprovider'), nullable=False),
    sa.Column('tracking_number', sa.String(), nullable=False),
    sa.Column('tracking_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('LABEL_CREATED', 'PICKED_UP', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'EXCEPTION', 'RETURNED', name='shippingstatus'), nullable=True),
    sa.Column('carrier_service', sa.String(), nullable=True),
    sa.Column('locker_id', sa.String(), nullable=True),
    sa.Column('locker_address', sa.String(), nullable=True),
    sa.Column('estimated_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipping_cost', sa.String(), nullable=True),
    sa.Column('provider_data', sa.JSON(), nullable=True),
    sa.Column('tracking_events', sa.JSON(), nullable=True),
    sa.Column('label_url', sa.String(), nullable=True),
    sa.Column('label_pdf', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_shipments_id'), 'shipments', ['id'], unique=False)
    op.create_index(op.f('ix_shipments_tracking_number'), 'shipments', ['tracking_number'], unique=True)
    op.create_table('user_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address_type', sa.Enum('SHIPPING', 'BILLING', 'BOTH', name='addresstype'), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address_line1', sa.String(), nullable=False),
    sa.Column('address_line2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('preferred_shipping_provider', sa.Enum('INPOST', 'POCZTA_POLSKA', 'DHL', 'NOVA_POSHTA', name='shippingprovider'), nullable=True),
    sa.Column('inpost_locker_id', sa.String(), nullable=True),
    sa.Column('inpost_locker_address', sa.String(), nullable=True),
    sa.Column('nova_poshta_city', sa.String(), nullable=True),
    sa.Column('nova_poshta_warehouse', sa.String(), nullable=True),
    sa.Column('nova_poshta_warehouse_address', sa.String(), nullable=True),
    sa.Column('dhl_service_point_id', sa.String(), nullable=True),
    sa.Column('dhl_service_point_address', sa.String(), nullable=True),
    sa.Column('delivery_notes', sa.String(), nullable=True),
    sa.Column('delivery_preferences', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_addresses_id'), 'user_addresses', ['id'], unique=False)
    op.create_index(op.f('ix_user_addresses_user_id'), 'user_addresses', ['user_id'], unique=False)
    op.create_table('made_to_order_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('customer_email', sa.String(), nullable=False),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('custom_text', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_made_to_order_requests_id'), 'made_to_order_requests', ['id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_title', sa.String(), nullable=False),
    sa.Column('product_sku', sa.String(), nullable=True),
    sa.Column('product_image', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('alt_text', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_id'), 'product_images', ['id'], unique=False)
    op.create_table('product_sales_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.Column('total_sold', sa.Integer(), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('last_view_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sale_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_sales_stats_id'), 'product_sales_stats', ['id'], unique=False)
    op.create_index(op.f('ix_product_sales_stats_product_id'), 'product_sales_stats', ['product_id'], unique=False)
    op.create_table('product_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('referrer', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_views_id'), 'product_views', ['id'], unique=False)
    op.create_index(op.f('ix_product_views_product_id'), 'product_views', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_views_viewed_at'), 'product_views', ['viewed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_views_viewed_at'), table_name='product_views')
    op.drop_index(op.f('ix_product_views_product_id'), table_name='product_views')
    op.drop_index(op.f('ix_product_views_id'), table_name='product_views')
    op.drop_table('product_views')
    op.drop_index(op.f('ix_product_sales_stats_product_id'), table_name='product_sales_stats')
    op.drop_index(op.f('ix_product_sales_stats_id'), table_name='product_sales_stats')
    op.drop_table('product_sales_stats')
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_made_to_order_requests_id'), table_name='made_to_order_requests')
    op.drop_table('made_to_order_requests')
    op.drop_index(op.f('ix_user_addresses_user_id'), table_name='user_addresses')
    op.drop_index(op.f('ix_user_addresses_id'), table_name='user_addresses')
    op.drop_table('user_addresses')
    op.drop_index(op.f('ix_shipments_tracking_number'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_products_title_uk'), table_name='products')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_users_password_reset_code'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email_verification_token'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_daily_sales_stats_id'), table_name='daily_sales_stats')
    op.drop_index(op.f('ix_daily_sales_stats_date'), table_name='daily_sales_stats')
    op.drop_table('daily_sales_stats')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
